# Generated by Django 3.2.4 on 2021-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/blog_pictures', verbose_name='Изображение'),
        ),
    ]
