# Generated by Django 3.2.4 on 2021-06-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
